export const reactRules = {
  'react/self-closing-comp': 'off',
  'react/destructuring-assignment': 'off',
  'react/jsx-props-no-spreading': 'off',
  'react/button-has-type': 'off',
  'react/react-in-jsx-scope': 'off',
  'react/jsx-filename-extension': ['error', { extensions: ['.tsx', '.jsx'] }],
  'react/function-component-definition': 'off',
  'react/jsx-one-expression-per-line': 'off',
  'react/no-unknown-property': 'off',
  'react/jsx-no-target-blank': 'off',
  'react/require-default-props': 'off',
  'react/jsx-wrap-multilines': 'off',
  'react/jsx-closing-bracket-location': 'off',
  'react/jsx-no-useless-fragment': 'off',
}
